# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cdabfbadd66a56f76f44aecc2f1f416e771f86e150e66b94299e401ba6bb2e39e38c1e1a6ea495905bb884c09b8c5d24c0d4e7e0f1783cf288d562228e06d6c

test:
  secret_key_base: f02b82e1a269ef357547f572229bccf37d9e0f40d8eb322b61c28d56b971c0d9ac79db340c1e2a79c8ec146f7593730b3a0e4c79f972f8d58a6552fe4d38cac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
